### ISSUE TITLE
Чистая установка на Ubuntu server

### ISSUE THREAD

**Issue by angel13rus** [pfzim/ldap-phonebook#33]
А можно опубликовать пошаговую инструкцию для установки на голую UBUNTU?

**Comment by angel13rus** [comment]
1. Установить Ubuntu server
2. Установить следующие компоненты:
 a. apache2
 b. mysql
 c. php
 d......
 e......
 3. Установка Клонировать комплект с гитхаба
 git clone https://github.com/pfzim/ldap-phonebook.git

**Comment by angel13rus** [comment]
Сам спросил, сам ответил. )))
#############Установка LDAP Phonebook на Ubuntu 20.04
######Установка Java на Ubuntu 20.04
1. Установка OpenJDK 11
Запустите приведенную ниже команду, чтобы установить пакет OpenJDK 11 в вашей системе.

sudo apt update
sudo apt install openjdk-11-jdk
После завершения установки проверим версию Java:

java -version

2. Установка OpenJDK 8
Java 8 является предыдущей стабильной версией, над ней работает большинство java-приложений. Запустите приведенную ниже команду, чтобы установить пакет OpenJDK 8 в вашей системе.

sudo apt update
sudo apt install openjdk-8-jdk
Проверим версию после установки:

Переключение между несколькими версиями Java
Большинство систем на основе Unix/Linux позволяет устанавливать несколько версий Java в одной системе. Вы можете изменить версию Java по умолчанию в соответствии с вашими требованиями.

Варианты обновления предоставляют возможность поддерживать символические ссылки для команд по умолчанию. Чтобы изменить версию Java по умолчанию, выполним команду на терминале:

Данная команда покажет список всех двоичных файлов Java, установленных в системе. Введите число, чтобы выбрать версию Java по умолчанию, и нажмите Enter.

При успешном выполнении вышеупомянутой команды снова запустите команду java -version, чтобы проверить текущую версию Java по умолчанию.

########УСТАНОВКА СТЕКА LAMP В UBUNTU 20.04

1: Установка Apache и настройка брандмауэра

sudo apt update
sudo apt install apache2

sudo ufw app list
sudo ufw allow in "Apache"

-----Также можно при помощи утилиты curl запросить свой адрес у третьей стороны.
curl http://icanhazip.com

-----Нужно отредактировать файл /etc/apache2/mods-enabled/dir.conf и изменить порядок файлов в директиве DirectoryIndex. Откройте файл.

#sudo nano /etc/apache2/mods-enabled/dir.conf

Поставьте index.php перед index.html:

<IfModule mod_dir.c>
DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
</IfModule>

Сохраните файл, а затем перезапустите веб-сервер:

#sudo systemctl reload apache2

-----Создание виртуального хоста
#sudo mkdir /var/www/pb
Затем определите права на каталог:
#sudo chown -R www-data:www-data /var/www/pb
Затем создайте новый файл в каталоге sites-available с помощью nano или другого текстового редактора:
#sudo nano /etc/apache2/sites-available/pb.conf
Вставьте в пустой файл эту базовую конфигурацию:
<VirtualHost *:80>
ServerName pb.domen.ru
ServerAlias phonebook.domen.ru
ServerAlias pb.domen.local
ServerAlias phonebook.domen.local
ServerAdmin it@domen.ru
DocumentRoot /var/www/pb
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

Теперь вы можете использовать a2ensite для включения этого виртуального хоста:
#sudo a2ensite pb

Возможно, вы захотите отключить веб-сайт по умолчанию, который устанавливается вместе с Apache. Это необходимо, если вы не используете пользовательский домен, потому что в этом случае конфигурация Apache по умолчанию перезапишет ваш виртуальный хост. Чтобы отключить веб-сайт Apache по умолчанию, введите:

#sudo a2dissite 000-default

Проверьте ошибки в конфигурации:
#sudo apache2ctl configtest

Если ошибок нет, команда вернет:
Syntax OK

Перезапустите Apache, чтобы обновить настройки:
#sudo systemctl reload apache2

Теперь Apache обслуживает домен вашего нового сайта. Но пока что каталог /var/www/pb все еще пуст. Давайте мы создадим файл index.html, чтобы протестировать новый сайт.

#nano /var/www/pb/index.php

Вставьте в файл такие строки:
<h1>It works!</h1>
<p>This is the landing page of <strong>your_domain</strong>.</p>

Откройте браузер и посетите домен или IP вашего сервера:
http://pb.domen.local - Локальное имя хоста
http://pb.domen.ru - Внешнее имя хоста, Если публикуете во вне. Проверить настройки Фаервола и NAT.
Либо по IP http://192.168.XXX.XXX

Вы должны увидеть такое сообщение:
It works!
This is the landing page of your_domain

Если вы видите эту страницу, ваш виртуальный хост Apache работает должным образом.


2: Установка MySQL
#sudo apt install mysql-server

После установки системе MySQL требуется настройка. Чтобы защитить ваш экземпляр, можно запустить простой встроенный скрипт безопасности, который удалит потенциально рискованные настройки. Запустите этот скрипт:
#sudo mysql_secure_installation

После настройки откройте командную строку MySQL в терминале:
#sudo mysql
Чтобы закрыть консоль MySQL, введите:
#exit

3: Установка PHP
PHP – это серверный язык сценариев для написания динамических страниц. Он позволяет запускать сценарии, подключаться к БД MySQL и передавать обработанный контент в браузер для отображения.

PHP также можно установить с помощью менеджера apt. Вам также понадобятся вспомогательные пакеты php-mysql (для настройки взаимодействия PHP и MySQL) и libapache2-mod-php (который отвечает за работу Apache с PHP).

Чтобы установить все эти пакеты, введите команду:


#sudo apt-get install php libapache2-mod-php php-mysql php-ldap php-cli
#apt-cache show php-cli
#sudo apt-get install  

После завершения установки вы можете запросить версию PHP, чтобы убедиться, что все работает верно.

#php -v

Включение, выключение модулей PHP в Ubuntu
extension=php_ldap.dll
extension=php_fileinfo.dll

Включение
#sudo phpenmod -s apache2 ldap
#sudo phpenmod -s apache2 fileinfo
#sudo phpenmod -s apache2 mysqli
#sudo phpenmod -s apache2 pdo_mysql
#sudo service php7.4 reload

Раскоментить строки в:
#nano /etc/php/7.4/apache2/php.ini

extension=curl
extension=fileinfo
extension=ldap
extension=mysqli
extension=pdo_mysql

Теперь стек полностью установлен. Но прежде чем ставить на него приложение, нужно создать виртуальный хост Apache, а затем протестировать и исправить возможные ошибки.


4: Тестирование стека LAMP
Сейчас нужно убедиться в том, что веб-сервер взаимодействует с PHP. Для этого нужно создать простой сценарий PHP, info.php.

Создайте этот файл в корневом каталоге веб-сервера:
#nano /var/www/pb/info.php

На экране появится пустой файл. Поместите в него такой код:
<?php
phpinfo();
Сохраните и закройте файл.

Теперь попробуйте открыть его в браузере:
http://pb.domen.ru/info.php

На экране появится веб-страница, содержащая информацию о сервере (она также может пригодиться вам при отладке). Если такая страница появилась, веб-сервер обслуживает файлы PHP.

Важно! После проверки обязательно удалите этот файл, иначе любой пользователь сможет получить доступ к конфиденциальным данным о среде PHP и о вашем сервере Ubuntu.

#sudo rm /var/www/pb/info.php

В случае необходимости вы сможете быстро создать эту страницу снова.

6: Тестирование соединения базы данных с PHP (опционально)
Если вы хотите проверить, может ли PHP подключаться к MySQL и выполнять запросы к базе данных, вы можете создать тестовую таблицу с фиктивными данными и запросить ее содержимое из сценария PHP.

Сначала нам нужно создать тестовую базу данных и пользователя для доступа к ней.

На момент написания этого мануала mysqlnd (PHP-библиотека для MySQL) не поддерживает caching_sha2_authentication, стандартный метод аутентификации MySQL 8. Нам нужно создать нового пользователя с аутентификацией mysql_native_password, чтобы иметь возможность подключиться к БД MySQL из PHP.

Давайте создадим базу данных example_database и пользователя example_user (вы можете заменить эти имена другими значениями).

Чтобы создать новую базу данных, войдите в СУБД как root:

#sudo mysql

И выполните следующую команду из консоли MySQL:

>CREATE DATABASE pb;

Теперь можно создать нового пользователя и предоставить ему полные права на новую базу данных.

Следующая команда создаст пользователя, который поддерживает аутентификацию по методу mysql_native_password. Также команда определяет условный пароль этого пользователя (password), который вы должны заменить безопасным паролем.

>CREATE USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'PASSWORD';
>CREATE USER 'pb'@'%' IDENTIFIED WITH mysql_native_password BY 'PASSWORD';

Эта команда предоставит пользователю полные права доступа ко всем БД:

>GRANT ALL ON *.* TO 'root'@'%';
>GRANT ALL ON *.* TO 'pb'@'%';

В то же время она запретит ему создавать или изменять другие базы данных на вашем сервере.

После этого выйдите из оболочки MySQL:

>exit

Вы можете убедиться, что у нового пользователя есть соответствующие права доступа. Снова войдите в консоль MySQL, на этот раз с помощью новых учетных данных:

>mysql -u root -p

Обратите внимание на флаг -p в этой команде, он запрашивает пароль, который вы указали при создании пользователя example_user. После входа в консоль MySQL убедитесь, что у вас есть доступ к базе данных example_database:

SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| example_database   |
| information_schema |
+--------------------+
2 rows in set (0.000 sec)

Теперь создайте таблицу по имени todo_list. Для этого в консоли MySQL выполните следующую команду:

CREATE TABLE example_database.todo_list (
item_id INT AUTO_INCREMENT,
content VARCHAR(255),
PRIMARY KEY(item_id)
);

Вставьте в тестовую таблицу несколько строк данных. Для этого вы можете повторить следующую команду несколько раз, используя в ней разные значения:

INSERT INTO example_database.todo_list (content) VALUES ("My first important item");

Чтобы убедиться, что данные были успешно сохранены в вашей таблице, запустите:

SELECT * FROM *.todo_list;

Вы увидите следующий вывод:

+---------+--------------------------+
| item_id | content                  |
+---------+--------------------------+
|       1 | My first important item  |
|       2 | My second important item |
|       3 | My third important item  |
|       4 | and this one more thing  |
+---------+--------------------------+
4 rows in set (0.000 sec)

Убедившись, что в тестовой таблице есть данные, вы можете выйти из консоли MySQL:

exit

Теперь можно создать PHP-скрипт, который будет подключаться к MySQL и запрашивать контент. Создайте новый PHP-файл в корневом каталоге приложения.

#nano /var/www/pb/test_mysql.php

Добавьте в PHP-скрипт следующие строки. Такой скрипт PHP подключается к базе данных MySQL и запрашивает содержимое таблицы todo_list, отображая результаты на экране в виде списка. Если у вас есть проблема с подключением к базе данных, он выдаст исключение.

<?php
$user = "pb";
$password = "PASSWORD";
$database = "pb";
$table = "pb";
try {
$db = new PDO("mysql:host=localhost;dbname=$database", $user, $password);
echo "<h2>TODO</h2><ol>";
foreach($db->query("SELECT content FROM $table") as $row) {
echo "<li>" . $row['content'] . "</li>";
}
echo "</ol>";
} catch (PDOException $e) {
print "Error!: " . $e->getMessage() . "<br/>";
die();
}

Сохраните и закройте файл, когда закончите редактирование.

Теперь вы можете получить доступ к этой странице в своем веб-браузере, посетив домен, который вы указали в конфигурации веб-сервера. К нему нужно добавить секцию /test_mysql.php:

http://pb.domen.ru/test_mysql.php

Вы должны увидеть свой контент, который вы добавили в тестовую таблицу.

Это означает, что среда PHP может подключаться и взаимодействовать с вашим сервером MySQL.

#################Установка LDAP phonebook
С клонировать:
git clone https://github.com/pfzim/ldap-phonebook.git

Скопировать клонированное содержимое в /var/www/pb

Открыть в браузере install.php и заполнить предлагаемые параметры
Заменить изображения карт templ/map[1-5].png своими схемами
Дополнительные настройки в inc.config.php (опционально)

http://pb.domen.local - Локальное имя хоста
http://pb.domen.ru - Внешнее имя хоста, Если публикуете во вне. Проверить настройки Фаервола и NAT.
Либо по IP http://192.168.XXX.XXX

Для включения LDAP аутентификации в LDAP_ADMIN_GROUP_DN нужно указать группу AD через которую предоставляется доступ:
// Группа в AD с пользователями имеющими доступ на редактирование справочника
define('LDAP_ADMIN_GROUP_DN', 'CN=Phonebook admin,OU=Admin Roles,OU=Groups,OU=Company,DC=domain,DC=local');

Изменить количество и названия карт:
define('PB_MAPS_COUNT', 5);
$map_names = array('Floor 1', 'Floor 3', 'Floor 6', 'Floor 14', 'Floor 25');
Изменить язык (cпасибо @Impuls2003):

define('APP_LANGUAGE', 'ru');

Параметры LDAP_HOST и LDAP_PORT заменены на LDAP_URI. Пример: ldaps://dc-01 ldap://dc-02:389

**Comment by pfzim** [comment]
Спасибо за инструкцию!

Только зачем ставить Java? Она не требуется для работы справочника.
И пункт 2 избыточен. База данных и пользователь создаются инсталлятором

**Comment by angel13rus** [comment]
Ну там под свои задачи нужна. ))) Не за что.
Вам спасибо за столь полезный код.

вт, 22 июн. 2021 г., 14:03 pfzim ***@***.***>:

**Comment by im0t0** [comment]
Спасибо за инструкцию, но как-то она странно заканчивается.
>На экране появится пустой файл. Поместите в него такой код:

**Comment by pfzim** [comment]
На мой взгляд эта инструкция сильно избыточна. Достаточно установить Apache (nginx), MariaDB (MySQL), PHP и запустить install.php для создания БД и конфига.

**Comment by SManuchehr** [comment]
Ребята я все по инструкции сделал у меня не получается помогите

**Comment by pfzim** [comment]
Установка (install.php) прошла успешно? Что видно в логах Apache?

**Comment by SManuchehr** [comment]
Да успешно установлен.
вот лог брат 
 [Fri Jul 05 10:20:55.947160 2024] [php7:error] [pid 1037] [client 192.168.3.252:2224] PHP Fatal error:  Uncaught Exception: Core: Access denied for user 'dbuser'@'localhost' in /var/www/html/modules/Core.php:107\nS                                   tack trace:\n#0 /var/www/html/modules/Core.php(100): Core->error_ex()\n#1 /var/www/html/modules/MySQLDB.php(98): Core->error()\n#2 /var/www/html/modules/MySQLDB.php(223): MySQLDB->connect()\n#3 /var/www/html/module                                   s/Config.php(33): MySQLDB->select_ex()\n#4 /var/www/html/modules/Config.php(62): Config->load()\n#5 /var/www/html/modules/Config.php(80): Config->get_ex()\n#6 /var/www/html/pb.php(154): Config->get_global()\n#7 {ma                                   in}\n  thrown in /var/www/html/modules/Core.php on line 107

**Comment by SManuchehr** [comment]
192.168.3.252 - - [05/Jul/2024:10:57:41 +0000] "GET / HTTP/1.1" 302 224 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36                             (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
192.168.3.252 - - [05/Jul/2024:10:57:41 +0000] "GET /pb.php HTTP/1.1" 500 295 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/5                            37.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
