### ISSUE TITLE
ошибка NotAllFilled

### ISSUE THREAD

**Issue by serdgserdg** [pfzim/ldap-phonebook#49]
Имеется необходимость добавить в телефонный справочник дополнительную функцию "Регистрация переговорной комнаты"
Добавил новую таблицу со столбцами  "pb_ peregovorka"
добавил в header  дополнительное меню. 

создал  файл для получения данных из базы .
файл - routes/pk.php 

создал форму и заполнил ее.
файл - templates/tpl.pk.php

создал файл для редактирования и создания новых записей в таблицу.
файл - routes/pk_edit.php

основываясь на информации как в файлах    user_save.php и contact_save.php
создал для своих столбцов таблицы файл  routes/pk_save.php

добавил эти файлы в pb.php
$core->Router->add_route('pk', 'pk');
$core->Router->add_route('pk_edit', 'pk_edit', TRUE);
$core->Router->add_route('pk_save', 'pk_save', TRUE); 
в файле pb.js дописал
unction on_saved(action, data)
{
	if(action == 'permission_save')
	{
		//f_get_perms(data.pid);
		window.location = window.location;
	}
	else if(action == 'user_save')
	{
		window.location = window.location;
	}
	else if(action == 'pk_save')
	{
		window.location = window.location;
	}
***//

В итоге данные из таблицы отображаются, форма для создания новых записей и форма редактирования открывается.
Но при нажатии кнопки "OK"  в форме отображается сообщение "NotAllFilled"
Пробовал отключать эту проверку в созданных файлах но ничего не помогло.

**Comment by pfzim** [comment]
Не видя код сложно подсказать. Сообщение говорит, что не все обязательные поля заполнены.

**Comment by serdgserdg** [comment]
Посмотри пожалуйста где я допустил ошибку.
 
**файл -  templates/tpl.pk.php**
<?php include(TEMPLATES_DIR.'tpl.header.php'); ?>

<div>
	<div class="content-box">
		<h3><?php L('UsersManagement') ?></h3>
		<span id="add_new_user" class="command" onclick="f_show_form('<?php ln('pk_edit/0') ?>');"><?php L('AddPk') ?></span>

		<table id="table" class="main-table" width="100%">
			<thead>
			<tr>
				<th width="5%">ID</th>
				<th width="20%"><?php L('PuserName') ?></th>
				<th width="20%"><?php L('Pdata') ?></th>
				<th width="20%"><?php L('PdataReg') ?></th>
				<th width="20%"><?php L('PdataBron') ?></th>
				<th width="20%"><?php L('Pip') ?></th>
				<th width="20%"><?php L('Pver') ?></th>
				<th width="20%"><?php L('Operations') ?></th>
			</tr>
			</thead>
			<tbody id="table-data">
			<?php $i = 0; if($pk) foreach($pk as &$row) { ?>
				<tr id="<?php eh("row".$row['id']); ?>" data-id=<?php eh($row['id']);?>>
					<td><?php eh($row['id']); ?></td>
					<td><?php eh($row['PuserName']); ?></td>
					<td><?php eh($row['Pdata']); ?></td>
					<td><?php eh($row['PdataReg']); ?></td>
					<td><?php eh($row['PdataBron']); ?></td>
					<td><?php eh($row['Pip']); ?></td>
					<td><?php eh($row['Pver']); ?></td>
					<td>
						<span class="command" onclick="f_show_form('<?php ln('pk_edit/'.$row['id']) ?>');"><?php L('Edit') ?></span>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
		<br />
		<br />
<?php include(TEMPLATES_DIR.'tpl.universal-form.php'); ?>
<?php include(TEMPLATES_DIR.'tpl.form-upload.php'); ?>
<?php include(TEMPLATES_DIR.'tpl.map-container.php'); ?>
<?php include(TEMPLATES_DIR.'tpl.menu-contact.php'); ?>
<?php include(TEMPLATES_DIR.'tpl.footer.php'); ?> 







**файл - routes/pk.php**
<?php

function pk(&$core, $params, $post_data)
{
	if(!$core->UserAuth->check_permission(0, PB_ACCESS_ADMIN))
	{
		$error_msg = LL('AccessDeniedToSection').' 0 '.LL('forUser').' '.$core->UserAuth->get_login().'!';
		include(TEMPLATES_DIR.'tpl.message.php');
		exit;
	}

	$core->db->select_assoc_ex($pk, rpv('
		SELECT
			u.`id`,
			u.`PuserName`,
			u.`Pdata`,
			u.`PdataReg`,
			u.`PdataBron`,
			u.`Pip`,
			u.`Pver`
			FROM @peregovorka AS u
		WHERE u.`Pver` > 0
		ORDER BY u.`id`
	'));

	include(TEMPLATES_DIR.'tpl.pk.php');
}







**файл - routes/pk_edit.php**
<?php

function pk_edit(&$core, $params)
{
	$pk_id = intval(@$params[1]);

	assert_permission_ajax(0, PB_ACCESS_ADMIN);	// level 0 having Write access mean admin
	$result_json = array(
		'code' => 0,
		'message' => '',
		'errors' => array()
	);

	if($pk_id)
	{
		if(!$core->db->select_assoc_ex($pk, rpv('

		SELECT	u.`PuserName`, u.`Pdata`, u.`PdataReg`, u.`PdataBron`, u.`Pip`, u.`Pver` FROM @peregovorka AS u WHERE u.`id` = # LIMIT 1', $pk_id)))

		{
			echo '{"code": 1, "message": "Failed get permissions"}';
		}
		
		$pk = &$pk[0];
	}
	else
	{
		$pk = array(
			'PuserName' => '',
			'Pdata' => '',
			'PdataReg' => '',
			'PdataBron' => '',
			'Pip' => '',
			'Pver' => ''
		);
	}

	$result_json = array(
		'code' => 0,
		'message' => '',
		'title' => LL('AddPk'),
		'action' => 'contact_save',
		'fields' => array(
			array(
				'type' => 'hidden',
				'name' => 'id',
				'value' => $pk_id
			),
			array(
				'type' => 'string',
				'name' => 'PuserName',
				'title' => LL('PuserName'),
				'value' => $pk['PuserName']
			),
			array(
				'type' => 'string',
				'name' => 'Pdata',
				'title' => LL('Pdata'),
				'value' => $pk['Pdata']
			),
			array(
				'type' => 'string',
				'name' => 'PdataReg',
				'title' => LL('PdataReg'),
				'value' => $pk['PdataReg']
			),
			array(
				'type' => 'string',
				'name' => 'PdataBron',
				'title' => LL('PdataBron'),
				'value' => $pk['PdataBron']
			),
			array(
				'type' => 'string',
				'name' => 'Pip',
				'title' => LL('Pip'),
				'value' => $pk['Pip']
			),
			array(
				'type' => 'string',
				'name' => 'Pver',
				'title' => LL('Pver'),
				'value' => $pk['Pver']
			)
		)
	);

	echo json_encode($result_json);


} 






**файл - routes/pk_save.php**
 <?php

function pk_save(&$core, $params, $post_data)
{
	$result_json = array(
		'code' => 0,
		'message' => '',
		'errors' => array()
	);

	assert_permission_ajax(0, PB_ACCESS_ADMIN);
	

	$pk_id = intval(@$post_data['id']);
	$PuserName = @$post_data['PuserName'];
	$Pdata = @$post_data['Pdata'];
   $PdataReg = @$post_data['PdataReg'];
   $PdataBron = @$post_data['PdataBron'];
   $Pip = @$post_data['Pip'];
   $Pver = @$post_data['Pver'];

	if(empty($PuserName))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'PuserName', 'msg' => LL('ThisFieldRequired'));
	}

	if(empty($Pdata))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'Pdata', 'msg' => LL('ThisFieldRequired'));
	}

	if($result_json['code'])
	{
		$result_json['message'] = LL('Not_All_Filled');
	}
	elseif($core->pkAuth->set_pk_info_ex($pk_id, $PuserName, $Pdata))
	{
		log_db('Updated pk', '{id='.$pk_id.',PuserName="'.$PuserName.'"}', 0);
		$result_json['message'] = LL('SuccessfulUpdated');
	}
	else
	{
		$result_json['code'] = 1;
		$result_json['message'] = LL('Error').': '.$core->get_last_error();
	}

	//log_file('Password changed: '.json_encode($result_json, JSON_UNESCAPED_UNICODE));
	echo json_encode($result_json, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
}

**Comment by serdgserdg** [comment]
**файл - routes/pk.php**
`<?php

function pk(&$core, $params, $post_data)
{
	if(!$core->UserAuth->check_permission(0, PB_ACCESS_ADMIN))
	{
		$error_msg = LL('AccessDeniedToSection').' 0 '.LL('forUser').' '.$core->UserAuth->get_login().'!';
		include(TEMPLATES_DIR.'tpl.message.php');
		exit;
	}

	$core->db->select_assoc_ex($pk, rpv('
		SELECT
			u.`id`,
			u.`PuserName`,
			u.`Pdata`,
			u.`PdataReg`,
			u.`PdataBron`,
			u.`Pip`,
			u.`Pver`
			FROM @peregovorka AS u
		WHERE u.`Pver` > 0
		ORDER BY u.`id`
	'));

	include(TEMPLATES_DIR.'tpl.pk.php');
}
`

**Comment by serdgserdg** [comment]
**файл - routes/pk_edit.php**
`<?php

function pk_edit(&$core, $params)
{
	$pk_id = intval(@$params[1]);

	assert_permission_ajax(0, PB_ACCESS_ADMIN);	// level 0 having Write access mean admin
	$result_json = array(
		'code' => 0,
		'message' => '',
		'errors' => array()
	);

	if($pk_id)
	{
		if(!$core->db->select_assoc_ex($pk, rpv('

		SELECT	u.`PuserName`, u.`Pdata`, u.`PdataReg`, u.`PdataBron`, u.`Pip`, u.`Pver` FROM @peregovorka AS u WHERE u.`id` = # LIMIT 1', $pk_id)))

		{
			echo '{"code": 1, "message": "Failed get permissions"}';
		}
		
		$pk = &$pk[0];
	}
	else
	{
		$pk = array(
			'PuserName' => '',
			'Pdata' => '',
			'PdataReg' => '',
			'PdataBron' => '',
			'Pip' => '',
			'Pver' => ''
		);
	}

	$result_json = array(
		'code' => 0,
		'message' => '',
		'title' => LL('AddPk'),
		'action' => 'contact_save',
		'fields' => array(
			array(
				'type' => 'hidden',
				'name' => 'id',
				'value' => $pk_id
			),
			array(
				'type' => 'string',
				'name' => 'PuserName',
				'title' => LL('PuserName'),
				'value' => $pk['PuserName']
			),
			array(
				'type' => 'string',
				'name' => 'Pdata',
				'title' => LL('Pdata'),
				'value' => $pk['Pdata']
			),
			array(
				'type' => 'string',
				'name' => 'PdataReg',
				'title' => LL('PdataReg'),
				'value' => $pk['PdataReg']
			),
			array(
				'type' => 'string',
				'name' => 'PdataBron',
				'title' => LL('PdataBron'),
				'value' => $pk['PdataBron']
			),
			array(
				'type' => 'string',
				'name' => 'Pip',
				'title' => LL('Pip'),
				'value' => $pk['Pip']
			),
			array(
				'type' => 'string',
				'name' => 'Pver',
				'title' => LL('Pver'),
				'value' => $pk['Pver']
			)
		)
	);

	echo json_encode($result_json);


} 
`

**Comment by serdgserdg** [comment]
**файл - routes/pk_save.php**
`
 <?php

function pk_save(&$core, $params, $post_data)
{
	$result_json = array(
		'code' => 0,
		'message' => '',
		'errors' => array()
	);

	assert_permission_ajax(0, PB_ACCESS_ADMIN);
	

	$pk_id = intval(@$post_data['id']);
	$PuserName = @$post_data['PuserName'];
	$Pdata = @$post_data['Pdata'];
   $PdataReg = @$post_data['PdataReg'];
   $PdataBron = @$post_data['PdataBron'];
   $Pip = @$post_data['Pip'];
   $Pver = @$post_data['Pver'];

	if(empty($PuserName))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'PuserName', 'msg' => LL('ThisFieldRequired'));
	}

	if(empty($Pdata))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'Pdata', 'msg' => LL('ThisFieldRequired'));
	}

	if($result_json['code'])
	{
		$result_json['message'] = LL('Not_All_Filled');
	}
	elseif($core->pkAuth->set_pk_info_ex($pk_id, $PuserName, $Pdata))
	{
		log_db('Updated pk', '{id='.$pk_id.',PuserName="'.$PuserName.'"}', 0);
		$result_json['message'] = LL('SuccessfulUpdated');
	}
	else
	{
		$result_json['code'] = 1;
		$result_json['message'] = LL('Error').': '.$core->get_last_error();
	}

	//log_file('Password changed: '.json_encode($result_json, JSON_UNESCAPED_UNICODE));
	echo json_encode($result_json, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
}
`

**Comment by serdgserdg** [comment]
в таблице все столбцы TEXT

**Comment by pfzim** [comment]
Файл **routes/pk_edit.php**
`'action' => 'contact_save',`
должно быть
`'action' => 'pk_save',`

**Comment by serdgserdg** [comment]
исправил
теперь выдает ошибку в var/pb/pb.log

2022-04-05T14:28:35+03:00  Exception: File: /var/www/pb/modules/Core.php[107]: Core: ERROR: Module /var/www/pb/modules/pkAuth.php not found! Trace: #0 /var/www/pb/modules/Core.php(100): Core->error_ex()
#1 /var/www/pb/modules/Core.php(56): Core->error()
#2 /var/www/pb/modules/Core.php(74): Core->load_ex()
#3 /var/www/pb/routes/pk_save.php(38): Core->__get()
#4 /var/www/pb/modules/Router.php(103): pk_save()
#5 /var/www/pb/pb.php(320): Router->process()
#6 {main}

**Comment by pfzim** [comment]
Вот здесь что-то непонятное:
```
	elseif($core->pkAuth->set_pk_info_ex($pk_id, $PuserName, $Pdata))
```

Видимо здесь надо запись в БД делать, как тут:
https://github.com/pfzim/ldap-phonebook/blob/ca5591dbe25abd9a40df64356bdb18fbd0f469f2/routes/contact_save.php#L65-L163

**Comment by serdgserdg** [comment]
elseif($core->pkAuth->set_pk_info_ex($pk_id, $PuserName, $Pdata))
заменил на
elseif(empty($user_id))

**Comment by serdgserdg** [comment]
**файл - routes/pk_save.php**
поправил но выдает ошибку
2022-04-05T16:50:00+03:00  Exception: File: /var/www/pb/routes/pk_save.php[78]: syntax error, unexpected variable "$pk_id", expecting ")" Trace: #0 /var/www/pb/pb.php(320): Router->process()
#1 {main}


`<?php`

function pk_save(&$core, $params, $post_data)
{
	assert_permission_ajax(0, PB_ACCESS_ADMIN);
	$result_json = array(
		'code' => 0,
		'message' => '',
		'errors' => array()
	);

        	$pk_id = intval(@$post_data['id']);
			$PuserName = trim(@$post_data['PuserName']);
			$Pdata = trim(@$post_data['Pdata']);
        	$PdataReg = trim(@$post_data['PdataReg']);
        	$PdataBron = trim(@$post_data['PdataBron']);
        	$Pip = trim(@$post_data['Pip']);
        	$Pver = trim(@$post_data['Pver']);

	if(empty($PuserName))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'PuserName', 'msg' => LL('ThisFieldRequired'));
	}

	if(empty($Pdata))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'Pdata', 'msg' => LL('ThisFieldRequired'));
	}

	if($result_json['code'])
	{
		$result_json['message'] = LL('NotAllFilled');
		echo json_encode($result_json);
		exit;
	}
   if(!$pk_id)
	{
		$core->db->put(rpv('
						INSERT INTO `@peregovorka`(
						`PuserName`, 
						`Pdata`, 
						`PdataReg`, 
						`PdataBron`, 
						`Pip`, 
						`Pver`
					) VALUES ({s0}, {s1}, {s2}, {s3}, {s4}, {s5}, {d6})
			',
			$PuserName,
			$Pdata,
        	$PdataReg,
        	$PdataBron,
        	$Pip,
        	$Pver
        	));
        	echo '{"code": 0, "id": '.$pk_id.', "message": "Added (ID '.$pk_id.')"}';
    }
	else
	{
		$core->db->put(rpv('
		    			UPDATE `@peregovorka` SET 
		    			`PuserName` = {s0}, 
						`Pdata` = {s1}, 
						`PdataReg = {s2}`, 
						`PdataBron` = {s3}, 
						`Pip` = {s4}, 
						`Pver` = {s5} 
						WHERE
					`id` = {d6} LIMIT 1
			',
			$PuserName,
			$Pdata,
        	$PdataReg,
        	$PdataBron,
        	$Pip,
        	$Pver
        	$pk_id
));
echo '{"code": 0, "id": '.$pk_id.',"message": "Updated (ID '.$pk_id.')"}'; 
}
}

**Comment by serdgserdg** [comment]
**Если в PHPMyAdmin сделать команду добавления то она добавляет строки**
INSERT INTO `pb_peregovorka`(`PuserName`, `Pdata`, `PdataReg`, `PdataBron`, `Pip`, `Pver`) VALUES ('nasonov', '01.04.2022', '01.04.2022', '01.04.2022', '192.168.140.102', '1');

**Comment by serdgserdg** [comment]
создал код который на добавление работает а на редактирование нет
`if(!$pk_id)`
	{
		$core->db->put(rpv("INSERT INTO `@peregovorka` (
						`PuserName`, 
						`Pdata`, 
						`PdataReg`, 
						`PdataBron`, 
						`Pip`, 
						`Pver`) 
						VALUES ('{$PuserName}', '{$Pdata}', '{$PdataReg}', '{$PdataBron}', '{$Pip}', '{$Pver}');")
		
        	);
        	echo '{"code": 0, "id": '.$pk_id.', "message": "Added (ID '.$pk_id.')"}';
    }
	else
	{
		$core->db->put(rpv("UPDATE `@peregovorka` SET (
						`PuserName`, 
						`Pdata`, 
						`PdataReg`, 
						`PdataBron`, 
						`Pip`, 
						`Pver`) 
						VALUES ('{$PuserName}', '{$Pdata}', '{$PdataReg}', '{$PdataBron}', '{$Pip}', '{$Pver}') WHERE `id` = '{$pk_id}';")
						);

**Comment by serdgserdg** [comment]
Похоже на то что он не берет из открывшейся формы данные или не видет $pk_id.
Может при редактировании нужно брать данные из массива который использует в pk_edit.php  $row['id'], тот ко которому заполняется форма для редактировани

**Comment by serdgserdg** [comment]
Вот так работает но форма не закрывается после нажатии кнопки "ОК"
не подскажете как сделать чтоб форма закрывалась?

`if(!$pk_id)
	{
		$core->db->put(rpv("INSERT INTO `@peregovorka` (
						`PuserName`, 
						`Pdata`, 
						`PdataReg`, 
						`PdataBron`, 
						`Pip`, 
						`Pver`) 
						VALUES ('{$PuserName}', '{$Pdata}', '{$PdataReg}', '{$PdataBron}', '{$Pip}', '{$Pver}');")
		        	);
		   $pk_id = $core->db->last_id();
        	echo '{"code": 0, "id": '.$pk_id.', "message": "Added (ID '.$pk_id.')"}';
        	    }
	else
	{
		$core->db->put(rpv("UPDATE `@peregovorka` SET
						`PuserName` = '{$PuserName}', 
						`Pdata` = '{$Pdata}', 
						`PdataReg` = '{$PdataReg}', 
						`PdataBron` = '{$PdataBron}', 
						`Pip` = '{$Pip}', 
						`Pver` = '{$Pver}' 
						WHERE `id` = '$pk_id';")
						);
echo '{"code": 0, "id": '.$pk_id.',"message": "Updated (ID '.$pk_id.')"}'; 
}`

**Comment by serdgserdg** [comment]
здесь что-то не так!

$pk_id = intval(@$post_data['id']);
$PuserName = trim(@$post_data['PuserName']);
$Pdata = trim(@$post_data['Pdata']);
$PdataReg = trim(@$post_data['PdataReg']);
$PdataBron = trim(@$post_data['PdataBron']);
$Pip = trim(@$post_data['Pip']);
$Pver = trim(@$post_data['Pver']);
Проверка на наличие данных
echo $pk_id;
echo $PuserName;
echo $Pdata;
echo $PdataReg;
echo $PdataBron;
echo $Pip;
echo $Pver;
Response: 21
sdf
sdf
sdf
sdf
sdf
1
Не могу понять почему отсутствуют значения?

**Comment by pfzim** [comment]
https://github.com/pfzim/ldap-phonebook/issues/49#issuecomment-1088732846
Вот этот вариант более правильный, просто запятой не хватает между:
```
        	$Pver
        	$pk_id

```

**Comment by serdgserdg** [comment]
ниже весь код pk_save.php, похоже что все правильно но на работает  при создании записи выдает ошибку
Exception: File: /var/www/pb/modules/Core.php[107]: Core: Column count doesn't match value count at row 1 Trace: 
#0 /var/www/pb/modules/Core.php(100): Core->error_ex() 
#1 /var/www/pb/modules/MySQLDB.php(296): Core->error() 
#2 /var/www/pb/routes/pk_save.php(40): MySQLDB->put() 
#3 /var/www/pb/modules/Router.php(103): pk_save() 
#4 /var/www/pb/pb.php(320): Router->process() 
#5 {main}




`<?php`

function pk_save(&$core, $params, $post_data)
{
	assert_permission_ajax(0, PB_ACCESS_ADMIN);
	$result_json = array(
		'code' => 0,
		'message' => '',
		'errors' => array()
	);

        	$pk_id = intval(@$post_data['id']);
			$PuserName = trim(@$post_data['PuserName']);
			$Pdata = trim(@$post_data['Pdata']);
        	$PdataReg = trim(@$post_data['PdataReg']);
        	$PdataBron = trim(@$post_data['PdataBron']);
        	$Pip = trim(@$post_data['Pip']);
        	$Pver = trim(@$post_data['Pver']);
		
	if(empty($PuserName))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'PuserName', 'msg' => LL('ThisFieldRequired'));
	}

	if(empty($Pdata))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'Pdata', 'msg' => LL('ThisFieldRequired'));
	}

	if($result_json['code'])
	{
		$result_json['message'] = LL('NotAllFilled');
		echo json_encode($result_json);
		exit;
	}
   if(!$pk_id)
	{
		$core->db->put(rpv('
				INSERT INTO `@peregovorka` (
						`PuserName`, 
						`Pdata`, 
						`PdataReg`, 
						`PdataBron`, 
						`Pip`, 
						`Pver`) 
						VALUES ({s0}, {s1}, {s2}, {s3}, {s4}, {s5}, {s6})
						',
						$PuserName,
						$Pdata,
						$PdataReg,
						$PdataBron,
						$Pip,
						$Pver
						));
		   $pk_id = $core->db->last_id();
echo '{"code": 0, "id": '.$pk_id.', "message": "Added (ID '.$pk_id.')"}';
	}
	else
	{
		$core->db->put(rpv('
		UPDATE `@peregovorka` SET 
		`PuserName` = {s0}, 
		`Pdata` = {s1}, 
		`PdataReg` = {s2}, 
		`PdataBron` = {s3}, 
		`Pip` = {s4}, 
		`Pver` = {s5}
		WHERE `id` = {s6} LIMIT 1
		',
		$PuserName,
		$Pdata,
		$PdataReg,
		$PdataBron,
		$Pip,
		$Pver
		));
echo '{"code": 0, "id": '.$pk_id.',"message": "Updated (ID '.$pk_id.')"}'; 
}
}

**Comment by pfzim** [comment]
```
<?php

function pk_save(&$core, $params, $post_data)
{
	assert_permission_ajax(0, PB_ACCESS_ADMIN);
	$result_json = array(
		'code' => 0,
		'message' => '',
		'errors' => array()
	);

        	$pk_id = intval(@$post_data['id']);
			$PuserName = trim(@$post_data['PuserName']);
			$Pdata = trim(@$post_data['Pdata']);
        	$PdataReg = trim(@$post_data['PdataReg']);
        	$PdataBron = trim(@$post_data['PdataBron']);
        	$Pip = trim(@$post_data['Pip']);
        	$Pver = trim(@$post_data['Pver']);
		
	if(empty($PuserName))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'PuserName', 'msg' => LL('ThisFieldRequired'));
	}

	if(empty($Pdata))
	{
		$result_json['code'] = 1;
		$result_json['errors'][] = array('name' => 'Pdata', 'msg' => LL('ThisFieldRequired'));
	}

	if($result_json['code'])
	{
		$result_json['message'] = LL('NotAllFilled');
		echo json_encode($result_json);
		exit;
	}
   if(!$pk_id)
	{
		$core->db->put(rpv('
				INSERT INTO `@peregovorka` (
						`PuserName`, 
						`Pdata`, 
						`PdataReg`, 
						`PdataBron`, 
						`Pip`, 
						`Pver`) 
						VALUES ({s0}, {s1}, {s2}, {s3}, {s4}, {s5})
						',
						$PuserName,
						$Pdata,
						$PdataReg,
						$PdataBron,
						$Pip,
						$Pver
						));
		   $pk_id = $core->db->last_id();
     	
        	echo '{"code": 0, "id": '.$pk_id.', "message": "Added (ID '.$pk_id.')"}';
	}
	else
	{
		$core->db->put(rpv('
		UPDATE `@peregovorka` SET 
		`PuserName` = {s0}, 
		`Pdata` = {s1}, 
		`PdataReg` = {s2}, 
		`PdataBron` = {s3}, 
		`Pip` = {s4}, 
		`Pver` = {s5}
		WHERE `id` = {d6} LIMIT 1
		',
		$PuserName,
		$Pdata,
		$PdataReg,
		$PdataBron,
		$Pip,
		$Pver,
		$pk_id
		));
		
		echo '{"code": 0, "id": '.$pk_id.',"message": "Updated (ID '.$pk_id.')"}'; 
	}
}
```

**Comment by serdgserdg** [comment]
Осталось теперь сделать функции: удаления строк, скрывания, поиска и фильтрации
