### ISSUE TITLE
Новая установка на Windows

### ISSUE THREAD

**Issue by dkhv** [pfzim/ldap-phonebook#78]
Что то не могу  понять что за ерунда.
новая установка и при синхронизации с LDAP ошибка
Exception: File: C:\xampp\htdocs\pb\modules\LDAP.php[47]: ldap_error(): Argument #1 ($ldap) must be of type resource, bool given Trace: #0 C:\xampp\htdocs\pb\modules\LDAP.php(47): ldap_error(false)
#1 C:\xampp\htdocs\pb\modules\LDAP.php(120): LDAP->connect()
#2 C:\xampp\htdocs\pb\routes\contacts_sync.php(26): LDAP->get_link()
#3 C:\xampp\htdocs\pb\modules\Router.php(103): contacts_sync(Object(Core), Array, Array)
#4 C:\xampp\htdocs\pb\pb.php(320): Router->process('contacts_sync', Array)
#5 {main}
очень похоже, что ошибка подключения. что не правильно?
	define('LDAP_URI', 'dlap://192.168.2.222');
	define('LDAP_USER', 'dv.local\\ad-reader');
	define('LDAP_PASSWD', 'Pa$$w0rd');
	define('LDAP_BASE_DN', 'DC=DV, DC=local');

**Comment by pfzim** [comment]
У вас опечатка в названии схемы. Должно быть `ldap://`

**Comment by dkhv** [comment]
исправил. теперь другая ошибка
Exception: File: C:\xampp\htdocs\pb\routes\contacts_sync.php[34]: ldap_search(): supplied argument is not a valid ldap link resource Trace: #0 C:\xampp\htdocs\pb\routes\contacts_sync.php(34): ldap_search(NULL, 'DC=DV=loc...', '(&(objectCatego...', Array, 0, 0, 0, 0, Array)
#1 C:\xampp\htdocs\pb\modules\Router.php(103): contacts_sync(Object(Core), Array, Array)
#2 C:\xampp\htdocs\pb\pb.php(320): Router->process('contacts_sync', Array)
#3 {main}

**Comment by pfzim** [comment]
При установке проверка подключения к LDAP проходила успешно?

**Comment by dkhv** [comment]
Да, все было хорошо

**Comment by pfzim** [comment]
Как тогда получилось, что в конфиге параметры неправильные?
Проблема именно в невозможности подключиться к LDAP.
Попробуйте так:
`define('LDAP_USER', 'dv\\ad-reader');`
или так:
`define('LDAP_USER', 'ad-reader@dv.local');`

**Comment by dkhv** [comment]
так получилось
define('LDAP_USER', 'ad-reader@dv.local');
